function g = surround(scale, config)
    g = model.data.decomposition.functions.opponent.rf.utils.gaussian(  ...
            [config.rf.size config.rf.size],                            ...
            (config.rf.surround.width * scale) ^ 2,                     ...
            (config.rf.surround.width * scale) ^ 2,                     ...
            0, 0,                                                       ...
            0.5,                                  ...
            [0 0]                                                       ...
        ) * config.rf.surround.weight;
end