function g = surround(scale, config)
    scale_factor = scale^0.8;
    g = model.data.rf.utils.gaussian(                                   ...
            [config.rf.so.size config.rf.so.size],                      ...
            (config.rf.so.surround.width * scale_factor),               ...
            (config.rf.so.surround.width * scale_factor),               ...
            0, 0,                                                       ...
            0.5,                                                        ...
            [0 0]                                                       ...
        ) * config.rf.so.surround.weight;
end