function g = center(scale, config)
    g = model.data.wavelet.functions.opponent.rf.utils.gaussian(        ...
            [config.rf.size config.rf.size],                            ...
            (config.rf.excitation.width * scale) ^ 2,                   ...
            (config.rf.excitation.width * scale) ^ 2,                   ...
            0, 0,                                                       ...
            config.rf.excitation.weight,                                ...
            [0 0]                                                       ...
        );
end

