function g = surround(scale, config)
    g = model.data.wavelet.functions.opponent.rf.utils.gaussian(        ...
            [config.rf.size config.rf.size],                            ...
            (config.rf.inhibition.width * scale) ^ 2,                   ...
            (config.rf.inhibition.width * scale) ^ 2,                   ...
            0, 0,                                                       ...
            config.rf.inhibition.weight,                                ...
            [0 0]                                                       ...
        ) * 0.95;   % Lennie & Haake
end