function g = center_top_middle(scale, config)
    g = model.data.decomposition.functions.opponent.rf.oriented.center(       ...
            scale,                                                      ...
            config,                                                     ...
            0,                                                          ...
            [-config.rf.center.offset 0]                                ...
        );
end