function g = center_top_left(scale, config)
    g = model.data.decomposition.functions.opponent.rf.oriented.center( ...
            scale,                                                      ...
            config,                                                     ...
            -45,                                                        ...
            [-config.rf.center.offset -config.rf.center.offset]         ...
        );
end