function g = surround(scale, config, angle, offset)
    g = model.data.decomposition.functions.opponent.rf.utils.gaussian(  ...
            [config.rf.size config.rf.size],                            ...
            (config.rf.surround.width  * scale) ^ 2,                    ...
            (config.rf.surround.length * scale) ^ 2,                    ...
            angle, 0,                                                   ...
            config.rf.surround.weight,                                  ...
            offset                                                      ...
        );
end