function g = surround_top_left(scale, config)
    g = model.data.decomposition.functions.opponent.rf.oriented.surround(   ...
            scale,                                                          ...
            config,                                                         ...
            -45,                                                            ...
            [-config.rf.surround.offset -config.rf.surround.offset]         ...
        );
end