function g = surround_top_middle(scale, config)
    g = model.data.decomposition.functions.opponent.rf.oriented.surround(   ...
            scale,                                                          ...
            config,                                                         ...
            0,                                                              ...
            [-config.rf.surround.offset 0]                                  ...
        );
end