function g = center_top_left(scale, config)
    g = model.data.wavelet.functions.opponent.rf.oriented.center(       ...
            scale,                                                      ...
            config,                                                     ...
            -45,                                                        ...
            [-config.rf.excitation.offset -config.rf.excitation.offset] ...
        );
end