function g = surround(scale, config, angle, offset)
    g = model.data.wavelet.functions.opponent.rf.utils.gaussian(        ...
            [config.rf.size config.rf.size],                            ...
            (config.rf.inhibition.width  * scale) ^ 2,                  ...
            (config.rf.inhibition.length * scale) ^ 2,                  ...
            angle, 0,                                                   ...
            config.rf.inhibition.weight,                                ...
            offset                                                      ...
        );
end