function g = surround_top_left(scale, config)
    g = model.data.wavelet.functions.opponent.rf.oriented.surround(     ...
            scale,                                                      ...
            config,                                                     ...
            -45,                                                        ...
            [-config.rf.inhibition.offset -config.rf.inhibition.offset] ...
        );
end