function x_ee = apply_excitation(gx_padded, orient_interactions, scale_interactions, config)
    x_ee = model.terms.interactions.orients.apply(...
            gx_padded, orient_interactions.JW.J_fft, scale_interactions, config ...
           );
end

