function g = center(scale, config, angle, offset)
    % TODO adjust size by scale
    g = model.data.rf.utils.gaussian(                                   ...
            [config.rf.do.size config.rf.do.size],                      ...
            (config.rf.do.center.width  * scale) ^ 2,                   ...
            (config.rf.do.center.length * scale) ^ 2,                   ...
            angle, 0,                                                   ...
            config.rf.do.center.weight,                                 ...
            offset                                                      ...
        );
end