function g = center_top_left(scale, config)
    g = model.data.rf.oriented.center(                                  ...
            scale,                                                      ...
            config,                                                     ...
            -45,                                                        ...
            [-config.rf.do.center.offset -config.rf.do.center.offset]   ...
        );
end