function g = center_top_middle(scale, config)
    g = model.data.rf.oriented.center(                                  ...
            scale,                                                      ...
            config,                                                     ...
            0,                                                          ...
            [-config.rf.do.center.offset 0]                             ...
        ) * config.rf.do.center.weight;
end