function g = surround(scale, config, angle, offset)
    g = model.data.rf.utils.gaussian(                                   ...
            [config.rf.do.size config.rf.do.size],                      ...
            (config.rf.do.surround.width  * scale) ^ 2,                 ...
            (config.rf.do.surround.length * scale) ^ 2,                 ...
            angle, 0,                                                   ...
            1,                                                          ...
            offset                                                      ...
        ) * config.rf.do.surround.weight;
end