function g = surround_top_middle(scale, config)
    g = model.data.rf.oriented.surround(                                ...
            scale,                                                      ...
            config,                                                     ...
            0,                                                          ...
            [-config.rf.do.surround.offset 0]                           ...
        );
end