function g = surround(scale, config, angle, offset)
    scale_factor = scale^0.8;
    g = model.data.rf.utils.gaussian(                                   ...
            [config.rf.do.size config.rf.do.size],                      ...
            (config.rf.do.surround.width * scale_factor),               ...
            (config.rf.do.surround.length * scale_factor),              ...
            angle, 0,                                                   ...
            1,                                                          ...
            (offset * scale_factor)                                     ...
        ) * config.rf.do.surround.weight;
end